export const PAYMENTS_ORDER_STORE = Symbol("PAYMENTS_ORDER_STORE");
export const PAYMENTS_PAYMENT_STORE = Symbol("PAYMENTS_PAYMENT_STORE");
export const PAYMENTS_PROVIDER = Symbol("PAYMENTS_PROVIDER");
export const PAYMENTS_CHECKOUT_PREPARATION_SERVICE = Symbol("PAYMENTS_CHECKOUT_PREPARATION_SERVICE");
export const PAYMENTS_CHECKOUT_ACTION_SERVICE = Symbol("PAYMENTS_CHECKOUT_ACTION_SERVICE");
export const PAYMENTS_FINANCE_PRIVATE_OBJECT_STORAGE = Symbol("PAYMENTS_FINANCE_PRIVATE_OBJECT_STORAGE");
