export const PAYMENTS_ORDER_STORE = Symbol("PAYMENTS_ORDER_STORE");
export const PAYMENTS_PAYMENT_STORE = Symbol("PAYMENTS_PAYMENT_STORE");
export const PAYMENTS_PROVIDER = Symbol("PAYMENTS_PROVIDER");
