export const CLIENT_BIRTH_PLACE_SEARCH_PROVIDER = Symbol("CLIENT_BIRTH_PLACE_SEARCH_PROVIDER");
export const CLIENT_PROFILE_READER = Symbol("CLIENT_PROFILE_READER");
export const CLIENT_PROFILE_STORE = Symbol("CLIENT_PROFILE_STORE");
