export const MOBILE_SESSION_UNIT_OF_WORK = Symbol("MOBILE_SESSION_UNIT_OF_WORK");
export const MOBILE_PASSWORDLESS_LOGIN_UNIT_OF_WORK = Symbol(
  "MOBILE_PASSWORDLESS_LOGIN_UNIT_OF_WORK"
);
export const MOBILE_PASSWORDLESS_REGISTRATION_UNIT_OF_WORK = Symbol(
  "MOBILE_PASSWORDLESS_REGISTRATION_UNIT_OF_WORK"
);
export const MOBILE_SESSION_AUTHENTICATION_STORE = Symbol("MOBILE_SESSION_AUTHENTICATION_STORE");
export const MOBILE_SESSION_MANAGEMENT_STORE = Symbol("MOBILE_SESSION_MANAGEMENT_STORE");
