export const ASTROLOGER_REVIEWS_READ_STORE = Symbol("ASTROLOGER_REVIEWS_READ_STORE");
export const ASTROLOGER_REVIEWS_COMMAND_STORE = Symbol("ASTROLOGER_REVIEWS_COMMAND_STORE");
export const ASTROLOGER_REVIEWS_AI_REPLY_DRAFT_STORE = Symbol(
  "ASTROLOGER_REVIEWS_AI_REPLY_DRAFT_STORE"
);
export const ASTROLOGER_REVIEWS_MESSAGING_STORE = Symbol("ASTROLOGER_REVIEWS_MESSAGING_STORE");
