export const PASSWORDLESS_CUSTOMER_ACCOUNT_REGISTRATION_SESSION_UNIT_OF_WORK = Symbol(
  "PASSWORDLESS_CUSTOMER_ACCOUNT_REGISTRATION_SESSION_UNIT_OF_WORK"
);

export const REGISTRATION_AUTH_OPTIONS = Symbol("REGISTRATION_AUTH_OPTIONS");
