export const ASTRO_DIARY_JOURNAL_READER = Symbol("ASTRO_DIARY_JOURNAL_READER");
export const ASTRO_DIARY_COMMAND_UNIT_OF_WORK = Symbol("ASTRO_DIARY_COMMAND_UNIT_OF_WORK");
export const ASTRO_DIARY_MEDIA_STORE = Symbol("ASTRO_DIARY_MEDIA_STORE");
export const ASTRO_DIARY_MEDIA_STORAGE = Symbol("ASTRO_DIARY_MEDIA_STORAGE");
