import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";

import { drizzle } from "drizzle-orm/node-postgres";
import { Client, Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { CHART_CALCULATION_TERMINAL_EVENT } from "@elevenhouse/domain";

import { assertFlowOutboxSafety } from "../../../scripts/flow-outbox-safety-reconciliation";
import { assertDevelopmentDatabaseUrl } from "../../connection";
import type { ElevenHouseDatabase } from "../../runtime";
import { createDrizzleFlowRuntimeDispatchOutboxStore } from "./drizzle-flow-runtime-dispatch-outbox-store";
import { readCurrentMigrationSql } from "../../testing/current-migration-sql";

const integrationDatabaseUrl = getIntegrationDatabaseUrl(process.env.INTEGRATION_DATABASE_URL);
const integrationBaselineSql = process.env.FLOW_INTEGRATION_BASELINE_PATH ? readFileSync(process.env.FLOW_INTEGRATION_BASELINE_PATH, "utf8") : readCurrentMigrationSql();
const databaseName = `elevenhouse_flow_outbox_${randomUUID().replaceAll("-", "")}`;
const isolatedDatabaseUrl = withDatabaseName(integrationDatabaseUrl, databaseName);
const adminClient = new Client({ connectionString: integrationDatabaseUrl });
const bookingEnrollmentEventType = "flows.booking_confirmed.enrollment_requested.v1";
const bookingLifecycleEventType = "bookings.lifecycle_event.dispatch_requested.v1";
let runtime: {
  readonly pool: Pool;
  readonly database: ElevenHouseDatabase;
  readonly close: () => Promise<void>;
};

describe("flow runtime dispatch outbox store Drizzle/PostgreSQL integration", () => {
  beforeAll(async () => {
    await adminClient.connect();
    await adminClient.query(`CREATE DATABASE "${databaseName}"`);
    const pool = new Pool({ connectionString: isolatedDatabaseUrl });
    runtime = {
      pool,
      database: drizzle(pool) as unknown as ElevenHouseDatabase,
      close: () => pool.end()
    };
    await runtime.pool.query(integrationBaselineSql);
  }, 30_000);

  afterAll(async () => {
    try {
      await runtime?.close();
      await adminClient.query(`DROP DATABASE IF EXISTS "${databaseName}" WITH (FORCE)`);
    } finally {
      await adminClient.end();
    }
  }, 30_000);

  beforeEach(async () => {
    await runtime.pool.query("delete from outbox_events");
  });

  it.skipIf(Boolean(process.env.FLOW_INTEGRATION_BASELINE_PATH))(
    "matches the exact outbox safety catalog generated by the current baseline",
    async () => {
      const client = new Client({ connectionString: isolatedDatabaseUrl });
      await client.connect();
      try {
        await expect(assertFlowOutboxSafety(client)).resolves.toBeUndefined();
      } finally {
        await client.end();
      }
    }
  );

  it("claims only owned events once and consumes attempt budget with a monotonic fence", async () => {
    const removedGenericRuntimeEvent = await insertEvent({
      eventType: "flow.runtime.event.unowned.v1"
    });
    const bookingEnrollmentEvent = await insertEvent({ eventType: bookingEnrollmentEventType });
    const lifecycleEventId = randomUUID();
    const bookingLifecycleEvent = await insertEvent({
      eventType: bookingLifecycleEventType,
      aggregateId: lifecycleEventId,
      payload: {
        schemaVersion: "booking-lifecycle-event-dispatch-request.v1",
        lifecycleEventId
      }
    });
    const chartJobId = randomUUID();
    const chartTerminalEvent = await insertEvent({
      eventType: CHART_CALCULATION_TERMINAL_EVENT,
      aggregateId: chartJobId,
      payload: {
        jobId: chartJobId,
        ownerUserId: randomUUID(),
        outcome: "succeeded",
        occurredAt: "2026-08-05T00:00:00.000Z"
      }
    });
    await insertEvent({ eventType: "calculation.pdf.requested.v1" });
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);

    const [first, second] = await Promise.all([
      store.claimBatch(claimInput()),
      store.claimBatch(claimInput())
    ]);
    const claims = [...first.claimed, ...second.claimed];

    expect(claims).toHaveLength(3);
    expect(claims).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          id: bookingEnrollmentEvent.id,
          eventType: bookingEnrollmentEventType,
          aggregateId: bookingEnrollmentEvent.aggregateId,
          attempts: 1,
          claimFence: 1n
        }),
        expect.objectContaining({
          id: bookingLifecycleEvent.id,
          eventType: bookingLifecycleEventType,
          aggregateId: lifecycleEventId,
          attempts: 1,
          claimFence: 1n
        }),
        expect.objectContaining({
          id: chartTerminalEvent.id,
          eventType: CHART_CALCULATION_TERMINAL_EVENT,
          aggregateId: chartJobId,
          attempts: 1,
          claimFence: 1n
        })
      ])
    );
    expect([...first.quarantined, ...second.quarantined]).toEqual([]);
    expect(await selectEvent(removedGenericRuntimeEvent.id)).toMatchObject({
      status: "pending",
      attempts: 0,
      claim_fence: "0",
      published_at: null,
      quarantined_at: null,
      quarantine_reason_code: null
    });
    expect(await selectEvent(bookingEnrollmentEvent.id)).toMatchObject({
      status: "publishing",
      attempts: 1,
      claim_fence: "1"
    });
  });

  it("rejects every stale disposition after reclaim and accepts the current fence", async () => {
    const fixture = await insertEvent();
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);
    const staleClaim = onlyClaim(await store.claimBatch(claimInput()));
    await runtime.pool.query(
      "update outbox_events set locked_at = transaction_timestamp() - interval '2 minutes' where id = $1",
      [fixture.id]
    );
    const currentClaim = onlyClaim(await store.claimBatch(claimInput()));

    expect(currentClaim).toMatchObject({ attempts: 2, claimFence: 2n });
    await expect(
      store.markPublished({ eventId: fixture.id, claimFence: staleClaim.claimFence })
    ).resolves.toEqual({ status: "stale" });
    await expect(
      store.markRetry({
        eventId: fixture.id,
        claimFence: staleClaim.claimFence,
        retryDelayMs: 1_000,
        reasonCode: "FLOW_RUNTIME_DISPATCH_RETRYABLE_FAILURE"
      })
    ).resolves.toEqual({ status: "stale" });
    await expect(
      store.markQuarantined({
        eventId: fixture.id,
        claimFence: staleClaim.claimFence,
        reasonCode: "FLOW_BOOKING_ENROLLMENT_PAYLOAD_INVALID"
      })
    ).resolves.toEqual({ status: "stale" });
    await expect(
      store.markPublished({ eventId: fixture.id, claimFence: currentClaim.claimFence })
    ).resolves.toEqual({ status: "applied" });

    expect(await selectEvent(fixture.id)).toMatchObject({
      status: "published",
      attempts: 2,
      claim_fence: "2",
      locked_at: null,
      quarantined_at: null,
      quarantine_reason_code: null,
      last_error: null
    });
  });

  it("schedules retry from database time and does not reclaim before it is due", async () => {
    const fixture = await insertEvent();
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);
    const claim = onlyClaim(await store.claimBatch(claimInput()));
    const beforeRetry = await runtime.pool.query<{ database_now: Date }>(
      "select transaction_timestamp() as database_now"
    );

    await expect(
      store.markRetry({
        eventId: fixture.id,
        claimFence: claim.claimFence,
        retryDelayMs: 60_000,
        reasonCode: "FLOW_RUNTIME_DISPATCH_RETRYABLE_FAILURE"
      })
    ).resolves.toEqual({ status: "applied" });

    const pending = await selectEvent(fixture.id);
    expect(pending).toMatchObject({
      status: "pending",
      attempts: 1,
      claim_fence: "1",
      locked_at: null,
      last_error: "FLOW_RUNTIME_DISPATCH_RETRYABLE_FAILURE"
    });
    expect(pending.available_at.getTime()).toBeGreaterThanOrEqual(
      beforeRetry.rows[0]!.database_now.getTime() + 59_000
    );
    await expect(store.claimBatch(claimInput())).resolves.toEqual({
      claimed: [],
      quarantined: []
    });

    await runtime.pool.query(
      "update outbox_events set available_at = transaction_timestamp() - interval '1 second' where id = $1",
      [fixture.id]
    );
    expect(onlyClaim(await store.claimBatch(claimInput()))).toMatchObject({
      attempts: 2,
      claimFence: 2n
    });
  });

  it("defers a disabled enrollment without consuming its retry budget", async () => {
    const fixture = await insertEvent({ eventType: bookingEnrollmentEventType });
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);
    const claim = onlyClaim(await store.claimBatch(claimInput()));
    const beforeDefer = await runtime.pool.query<{ database_now: Date }>(
      "select transaction_timestamp() as database_now"
    );

    await expect(
      store.markDeferred({
        eventId: fixture.id,
        claimFence: claim.claimFence,
        retryDelayMs: 60_000,
        reasonCode: "FLOW_BOOKING_ENROLLMENT_DEFERRED"
      })
    ).resolves.toEqual({ status: "applied" });

    const pending = await selectEvent(fixture.id);
    expect(pending).toMatchObject({
      status: "pending",
      attempts: 0,
      claim_fence: "1",
      locked_at: null,
      last_error: "FLOW_BOOKING_ENROLLMENT_DEFERRED"
    });
    expect(pending.available_at.getTime()).toBeGreaterThanOrEqual(
      beforeDefer.rows[0]!.database_now.getTime() + 59_000
    );
    await expect(store.claimBatch(claimInput())).resolves.toEqual({
      claimed: [],
      quarantined: []
    });

    await runtime.pool.query(
      "update outbox_events set available_at = transaction_timestamp() - interval '1 second' where id = $1",
      [fixture.id]
    );
    expect(onlyClaim(await store.claimBatch(claimInput()))).toMatchObject({
      attempts: 1,
      claimFence: 2n
    });
  });

  it("persists a terminal queryable quarantine and never claims it again", async () => {
    const fixture = await insertEvent({ payload: { secret: "do-not-persist-in-reason" } });
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);
    const claim = onlyClaim(await store.claimBatch(claimInput()));

    await expect(
      store.markQuarantined({
        eventId: fixture.id,
        claimFence: claim.claimFence,
        reasonCode: "FLOW_BOOKING_ENROLLMENT_PAYLOAD_INVALID"
      })
    ).resolves.toEqual({ status: "applied" });

    const quarantined = await selectEvent(fixture.id);
    expect(quarantined).toMatchObject({
      status: "quarantined",
      attempts: 1,
      claim_fence: "1",
      locked_at: null,
      published_at: null,
      quarantine_reason_code: "FLOW_BOOKING_ENROLLMENT_PAYLOAD_INVALID",
      last_error: "FLOW_BOOKING_ENROLLMENT_PAYLOAD_INVALID"
    });
    expect(quarantined.quarantined_at).toBeInstanceOf(Date);
    expect(quarantined.quarantine_reason_code).not.toContain("do-not-persist-in-reason");
    await expect(store.claimBatch(claimInput())).resolves.toEqual({
      claimed: [],
      quarantined: []
    });
  });

  it("quarantines an exhausted crashed claim exactly once without another dispatch attempt", async () => {
    const fixture = await insertEvent();
    const store = createDrizzleFlowRuntimeDispatchOutboxStore(runtime.database);
    expect(onlyClaim(await store.claimBatch(claimInput({ maxAttempts: 1 })))).toMatchObject({
      attempts: 1,
      claimFence: 1n
    });
    await runtime.pool.query(
      "update outbox_events set locked_at = transaction_timestamp() - interval '2 minutes' where id = $1",
      [fixture.id]
    );

    await expect(store.claimBatch(claimInput({ maxAttempts: 1 }))).resolves.toEqual({
      claimed: [],
      quarantined: [
        {
          id: fixture.id,
          eventType: bookingEnrollmentEventType,
          aggregateId: fixture.aggregateId,
          attempts: 1,
          reasonCode: "FLOW_RUNTIME_DISPATCH_RETRY_EXHAUSTED"
        }
      ]
    });
    await expect(store.claimBatch(claimInput({ maxAttempts: 1 }))).resolves.toEqual({
      claimed: [],
      quarantined: []
    });
    expect(await selectEvent(fixture.id)).toMatchObject({
      status: "quarantined",
      attempts: 1,
      claim_fence: "1",
      quarantine_reason_code: "FLOW_RUNTIME_DISPATCH_RETRY_EXHAUSTED"
    });
  });
});

function claimInput(overrides: { readonly maxAttempts?: number } = {}) {
  return {
    limit: 10,
    publishingLockTimeoutMs: 60_000,
    maxAttempts: overrides.maxAttempts ?? 3
  };
}

async function insertEvent(
  input: {
    readonly eventType?: string;
    readonly aggregateId?: string;
    readonly payload?: unknown;
  } = {}
): Promise<{ readonly id: string; readonly aggregateId: string }> {
  const id = randomUUID();
  const aggregateId = input.aggregateId ?? randomUUID();
  await runtime.pool.query(
    `insert into outbox_events (id, event_type, aggregate_id, payload)
     values ($1, $2, $3, $4)`,
    [id, input.eventType ?? bookingEnrollmentEventType, aggregateId, input.payload ?? { source: "test" }]
  );
  return { id, aggregateId };
}

async function selectEvent(id: string): Promise<{
  readonly status: string;
  readonly attempts: number;
  readonly claim_fence: string;
  readonly available_at: Date;
  readonly locked_at: Date | null;
  readonly published_at: Date | null;
  readonly quarantined_at: Date | null;
  readonly quarantine_reason_code: string | null;
  readonly last_error: string | null;
}> {
  const result = await runtime.pool.query(
    `select status, attempts, claim_fence, available_at, locked_at, published_at,
            quarantined_at, quarantine_reason_code, last_error
       from outbox_events where id = $1`,
    [id]
  );
  return result.rows[0]!;
}

function onlyClaim(
  batch: Awaited<
    ReturnType<ReturnType<typeof createDrizzleFlowRuntimeDispatchOutboxStore>["claimBatch"]>
  >
) {
  expect(batch.quarantined).toEqual([]);
  expect(batch.claimed).toHaveLength(1);
  return batch.claimed[0]!;
}

function getIntegrationDatabaseUrl(value: string | undefined): string {
  if (!value) throw new Error("INTEGRATION_DATABASE_URL is required");
  assertDevelopmentDatabaseUrl(value);
  return value;
}

function withDatabaseName(databaseUrl: string, name: string): string {
  const url = new URL(databaseUrl);
  url.pathname = `/${name}`;
  return url.toString();
}
