import type { PlatformPlan } from "./platform-billing-types";

export const platformPlanSeedData = [
  {
    id: "start",
    code: "start",
    name: "Старт",
    tagline: "Чтобы начать практику",
    monthlyPriceMinor: 0,
    yearlyPriceMinor: 0,
    currency: "RUB",
    platformFeeBps: 800,
    seatsLimit: 1,
    bookingsLimit: 30,
    aiRequestsLimit: 20,
    automationLimit: 1,
    isPopular: false,
    isActive: true,
    features: ["engine", "pdf", "natal", "numerology", "page", "calendar", "crm", "inbox", "refs"]
  },
  {
    id: "pro",
    code: "pro",
    name: "Pro",
    tagline: "Для активной практики",
    monthlyPriceMinor: 199000,
    yearlyPriceMinor: 1910000,
    currency: "RUB",
    platformFeeBps: 400,
    seatsLimit: 1,
    bookingsLimit: null,
    aiRequestsLimit: null,
    automationLimit: null,
    isPopular: true,
    isActive: true,
    features: [
      "engine",
      "pdf",
      "natal",
      "synastry",
      "forecast",
      "solar",
      "matrix",
      "numerology",
      "hd",
      "horar",
      "vedic",
      "astrocal",
      "child",
      "page",
      "products",
      "calendar",
      "crm",
      "funnels",
      "group",
      "ai",
      "aicontent",
      "triggers",
      "content",
      "autopost",
      "journal",
      "video",
      "recordings",
      "inbox",
      "analytics",
      "refs"
    ]
  },
  {
    id: "studio",
    code: "studio",
    name: "Studio",
    tagline: "Команда и масштаб",
    monthlyPriceMinor: 499000,
    yearlyPriceMinor: 4790000,
    currency: "RUB",
    platformFeeBps: 200,
    seatsLimit: 5,
    bookingsLimit: null,
    aiRequestsLimit: null,
    automationLimit: null,
    isPopular: false,
    isActive: true,
    features: [
      "engine",
      "pdf",
      "natal",
      "synastry",
      "forecast",
      "solar",
      "matrix",
      "numerology",
      "hd",
      "horar",
      "vedic",
      "astrocal",
      "child",
      "page",
      "products",
      "calendar",
      "crm",
      "funnels",
      "group",
      "ai",
      "aicontent",
      "triggers",
      "content",
      "autopost",
      "journal",
      "video",
      "recordings",
      "inbox",
      "analytics",
      "refs",
      "team",
      "whitelabel",
      "api",
      "priority"
    ]
  }
] as const satisfies readonly PlatformPlan[];
