export const CLIENT_COMMERCE_RELATIONSHIP_READER = Symbol("CLIENT_COMMERCE_RELATIONSHIP_READER");
export const CLIENT_COMMERCE_PRODUCT_STORE = Symbol("CLIENT_COMMERCE_PRODUCT_STORE");
export const CLIENT_COMMERCE_TARIFF_AUTHORITY_STORE = Symbol(
  "CLIENT_COMMERCE_TARIFF_AUTHORITY_STORE"
);
export const CLIENT_COMMERCE_FINANCE_POLICY_STORE = Symbol("CLIENT_COMMERCE_FINANCE_POLICY_STORE");
export const CLIENT_COMMERCE_AVAILABILITY_STORE = Symbol("CLIENT_COMMERCE_AVAILABILITY_STORE");
