export const MEDIA_ASSET_STORE = Symbol("MEDIA_ASSET_STORE");
export const MEDIA_OBJECT_STORAGE = Symbol("MEDIA_OBJECT_STORAGE");
export const MEDIA_PUBLIC_URL_RESOLVER = Symbol("MEDIA_PUBLIC_URL_RESOLVER");
export const MEDIA_PRIVATE_OBJECT_STORAGE = Symbol("MEDIA_PRIVATE_OBJECT_STORAGE");
export const MEDIA_ID_GENERATOR = Symbol("MEDIA_ID_GENERATOR");
