export const CLIENT_JOIN_PROFILE_READER = Symbol("CLIENT_JOIN_PROFILE_READER");
export const CLIENT_JOIN_STORE = Symbol("CLIENT_JOIN_STORE");
export const CLIENT_JOIN_OPTIONS = Symbol("CLIENT_JOIN_OPTIONS");
