export const SESSION_READ_STORE = Symbol("PUBLIC_SESSION_READ_STORE");
export const SESSION_COMMAND_STORE = Symbol("PUBLIC_SESSION_COMMAND_STORE");
export const SESSION_MEDIA_ROOM_PROVIDER = Symbol("PUBLIC_SESSION_MEDIA_ROOM_PROVIDER");
