export const MATRIX_REPORT_STORE = Symbol("MATRIX_REPORT_STORE");
export const MATRIX_PDF_JOB_STORE = Symbol("MATRIX_PDF_JOB_STORE");
export const MATRIX_REPORT_ID_GENERATOR = Symbol("MATRIX_REPORT_ID_GENERATOR");
