export const PASSWORDLESS_AUTH_UNIT_OF_WORK = Symbol("PASSWORDLESS_AUTH_UNIT_OF_WORK");
export const PASSWORDLESS_AUTH_OPTIONS = Symbol("PASSWORDLESS_AUTH_OPTIONS");
export const PASSWORDLESS_RATE_LIMITER = Symbol("PASSWORDLESS_RATE_LIMITER");
export const PASSWORDLESS_RATE_LIMIT_OPTIONS = Symbol("PASSWORDLESS_RATE_LIMIT_OPTIONS");
