export const PASSWORDLESS_AUTH_UNIT_OF_WORK = Symbol("PASSWORDLESS_AUTH_UNIT_OF_WORK");
export const PASSWORDLESS_AUTH_OPTIONS = Symbol("PASSWORDLESS_AUTH_OPTIONS");
export const AUTH_CODE_DELIVERY = Symbol("AUTH_CODE_DELIVERY");
