export const PUBLIC_BOOKING_COMMAND_STORE = Symbol("PUBLIC_BOOKING_COMMAND_STORE");
export const PUBLIC_BOOKING_AVAILABILITY_STORE = Symbol("PUBLIC_BOOKING_AVAILABILITY_STORE");
export const PUBLIC_BOOKING_CLIENT_READER = Symbol("PUBLIC_BOOKING_CLIENT_READER");
export const PUBLIC_BOOKING_PRODUCT_READER = Symbol("PUBLIC_BOOKING_PRODUCT_READER");
