export const SESSION_READ_STORE = Symbol("SESSION_READ_STORE");
export const SESSION_COMMAND_STORE = Symbol("SESSION_COMMAND_STORE");
export const SESSION_MEDIA_ROOM_PROVIDER = Symbol("SESSION_MEDIA_ROOM_PROVIDER");
