import type { DictionaryLocale } from "@elevenhouse/contracts";
import type { ChartEngineMode } from "./chartEngineMode";

const ruChartEngineCopy = {
  documentTitle: "ElevenHouse | Движок карт",
  title: "Движок карт",
  modes: {
    natal: {
      tab: "Натал",
      title: "Натальная карта",
      calculating: "Рассчитываем карту",
      calculationDetail: "Строим карту по данным рождения клиента.",
      emptyTitle: "Готово к расчёту натала",
      emptyDetail:
        "Выберите клиента с полной датой, временем, часовым поясом и координатами рождения.",
      readyDetail: "Данные рождения и настройки готовы для натальной карты.",
      successDetail: "Натальная карта рассчитана и привязана к клиенту.",
      staleDetail:
        "Данные рождения или настройки изменились. Пересчитайте натал, чтобы обновить колесо и таблицы.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать"
    },
    child_chart: {
      tab: "Детская",
      title: "Детская карта",
      calculating: "Рассчитываем детскую карту",
      calculationDetail: "Строим карту и открываем бережные трактовки для детского возраста.",
      emptyTitle: "Готово к расчёту детской карты",
      emptyDetail: "Выберите клиента, чтобы построить карту и открыть детские трактовки.",
      readyDetail: "Всё готово: построим карту и откроем детские трактовки.",
      successDetail:
        "Расчёт использует натальные положения; трактовки адаптированы для родительского чтения.",
      staleDetail: "Данные рождения или настройки изменились. Пересчитайте детскую карту.",
      staleAction: "Пересчитать детскую",
      calculateAction: "Рассчитать детскую"
    },
    transit: {
      tab: "Транзиты",
      title: "Транзитная карта",
      calculating: "Рассчитываем транзиты",
      calculationDetail: "Строим транзиты по данным рождения клиента и выбранному моменту.",
      emptyTitle: "Готово к расчёту транзитов",
      emptyDetail: "Выберите клиента и укажите дату, время и место транзита.",
      readyDetail: "Натал клиента и момент транзита готовы для расчёта.",
      successDetail: "Транзиты рассчитаны по наталу клиента и выбранному моменту.",
      staleDetail: "Данные рождения, настройки или момент транзита изменились. Пересчитайте карту.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать транзиты"
    },
    progression: {
      tab: "Прогрессии",
      title: "Прогрессии",
      calculating: "Рассчитываем прогрессии",
      calculationDetail: "Строим вторичные прогрессии на выбранную дату.",
      emptyTitle: "Готово к расчёту прогрессий",
      emptyDetail: "Выберите клиента и дату прогрессии.",
      readyDetail: "Натал клиента и дата прогрессии готовы для расчёта.",
      successDetail: "Прогрессии рассчитаны по наталу клиента и выбранной дате.",
      staleDetail:
        "Данные рождения, настройки или дата прогрессии изменились. Пересчитайте прогрессии.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать прогрессии"
    },
    synastry: {
      tab: "Синастрия",
      title: "Синастрия",
      calculating: "Рассчитываем синастрию",
      calculationDetail: "Строим карту совместимости по данным рождения двух клиентов.",
      emptyTitle: "Готово к расчёту синастрии",
      emptyDetail: "Выберите второго клиента для расчёта совместимости.",
      readyDetail: "Оба клиента готовы для расчёта совместимости.",
      successDetail: "Синастрия рассчитана для выбранной пары клиентов.",
      staleDetail: "Данные одного из участников или настройки изменились. Пересчитайте синастрию.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать синастрию"
    },
    composite: {
      tab: "Композит",
      title: "Композит",
      calculating: "Рассчитываем композит",
      calculationDetail: "Строим общую карту отношений по данным рождения двух клиентов.",
      emptyTitle: "Готово к расчёту композита",
      emptyDetail: "Выберите второго клиента для построения общей карты отношений.",
      readyDetail: "Оба клиента готовы для расчёта композитной карты.",
      successDetail: "Композит рассчитан как одно колесо отношений для выбранной пары.",
      staleDetail: "Данные одного из участников или настройки изменились. Пересчитайте композит.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать композит"
    },
    solar_return: {
      tab: "Соляр",
      title: "Соляр",
      calculating: "Рассчитываем соляр",
      calculationDetail: "Строим соляр на выбранный год.",
      emptyTitle: "Готово к расчёту соляра",
      emptyDetail: "Выберите клиента и год соляра.",
      readyDetail: "Натал клиента и год соляра готовы для расчёта.",
      successDetail: "Соляр рассчитан по наталу клиента и выбранному году.",
      staleDetail: "Данные рождения, настройки или год соляра изменились. Пересчитайте соляр.",
      staleAction: "Пересчитать карту",
      calculateAction: "Рассчитать соляр"
    },
    astrocartography: {
      tab: "Астрокарта",
      title: "Астрокартография",
      calculating: "Рассчитываем линии",
      calculationDetail: "Строим линии планет на карте мира по данным рождения клиента.",
      emptyTitle: "Готово к расчёту астрокарты",
      emptyDetail: "Выберите клиента для построения линий планет на карте мира.",
      readyDetail: "Натал клиента готов для расчёта линий на карте мира.",
      successDetail: "Линии планет рассчитаны по наталу клиента.",
      staleDetail: "Данные рождения или настройки изменились. Пересчитайте линии карты мира.",
      staleAction: "Пересчитать линии",
      calculateAction: "Рассчитать линии"
    },
    horary: {
      tab: "Хорар",
      title: "Хорар",
      calculating: "Рассчитываем хорар",
      calculationDetail: "Строим карту на момент вопроса.",
      emptyTitle: "Готово к хорару",
      emptyDetail: "Выберите клиента и заполните вопрос, момент и место вопроса.",
      readyDetail: "Введите вопрос и момент, чтобы построить карту вопроса.",
      successDetail: "Карта построена на момент вопроса; автоматический ответ не подключён.",
      staleDetail: "Вопрос, момент, место или настройки изменились. Пересчитайте карту.",
      staleAction: "Пересчитать хорар",
      calculateAction: "Рассчитать хорар"
    }
  } satisfies Record<ChartEngineMode, unknown>,
  modeMenu: {
    navigationLabel: "Тип карты",
    openLabel: "Открыть остальные типы карт",
    menuLabel: "Другие типы карт"
  },
  client: {
    label: "Клиент",
    choose: "Выберите клиента",
    fallbackInitial: "К",
    crmSource: "Дата рождения не указана",
    partnerLabel: "Партнёр",
    choosePartner: "Выберите партнёра",
    partnerFallbackInitial: "П",
    partnerPrefix: "Партнёр"
  },
  actionBar: {
    exportLabel: "Экспорт карты",
    exportUnavailable: "Экспорт карты пока недоступен",
    link: "Привязать",
    linked: "✓ Привязана",
    linkUnavailable: "Рассчитайте карту, чтобы привязать её к клиенту",
    birthData: "Данные рождения",
    settings: "Настройки",
    childPdfUnavailable: "PDF для детской карты пока недоступен",
    horaryPdfUnavailable: "PDF для хорара пока недоступен",
    methodPdfUnavailable: "PDF для этого типа карты пока недоступен",
    defaultPdfUnavailable: "PDF доступен после расчёта карты"
  },
  recovery: {
    regionLabel: "Восстановление данных расчёта",
    retryPoll: "Повторить проверку расчёта",
    retryResult: "Повторить загрузку результата",
    retrySaved: "Повторить загрузку сохранённого расчёта",
    retryLink: "Повторить привязку",
    recoverIdentity: "Открыть клиентов расчёта"
  },
  emptyClient: {
    title: "Выберите клиента",
    description: "Карта появится после выбора клиента."
  },
  rail: {
    ariaLabel: "Сводка карты",
    birthData: "Данные рождения",
    missing: (items: readonly string[]) => `Не хватает: ${items.join(", ")}.`,
    warnings: "Предупреждения",
    approximateWarning: "Время рождения указано примерно: дома и углы могут смещаться.",
    astrocartography: "Астрокарта",
    bigThree: "Большая тройка",
    linesPending: "Появится после расчёта линий.",
    chartPending: "Появится после расчёта.",
    retrogrades: "Ретроградные",
    noRetrogrades: "Нет в текущем результате.",
    elements: "Стихии",
    modalities: "Кресты",
    polarity: "Полярность",
    dominants: "Доминанты",
    aspectsShort: "асп.",
    insufficientAspects: "Недостаточно аспектов.",
    astroLines: "Линии",
    astroPlanets: "Планеты",
    astroAngles: "Углы",
    sun: "Солнце",
    moon: "Луна"
  },
  distributions: {
    elements: { fire: "Огонь", earth: "Земля", air: "Воздух", water: "Вода" },
    modalities: {
      cardinal: "Кардинальный",
      fixed: "Фиксированный",
      mutable: "Мутабельный"
    },
    polarity: { masculine: "Мужская", feminine: "Женская" }
  },
  panel: {
    ariaLabel: "Данные карты",
    settingsTitle: "Настройки расчёта",
    closeSettings: "Закрыть настройки расчёта",
    tabs: {
      planets: "Планеты",
      aspects: "Аспекты",
      houses: "Дома",
      interpretations: "Трактовки",
      ai: "AI"
    }
  },
  view: {
    selectClientStatus: "Выберите клиента",
    selectClientDetail: "Выберите клиента для построения карты.",
    calculatingStatus: "Расчёт выполняется",
    calculatingDetail: "Подготавливаем карту.",
    calculatingAction: "Рассчитываем",
    failedStatus: "Ошибка расчёта",
    failedDetail: "Проверьте данные рождения клиента и повторите расчёт.",
    retryCalculation: "Повторить расчёт",
    staleStatus: "Требуется пересчёт",
    currentStatus: "Актуальная карта",
    currentAction: "Актуальна",
    readyStatus: "Готово к расчёту",
    approximateStatus: "Время примерно",
    approximateDetail: "Расчёт доступен, но карта получит предупреждение о точности времени.",
    approximateAction: "Рассчитать с пометкой",
    missingDateStatus: "Нужна дата рождения",
    missingDateDetail: "Заполните дату рождения в карточке клиента.",
    addDateAction: "Добавьте дату",
    missingTimeStatus: "Нужно время рождения",
    missingTimeDetail: "Без времени рождения не строим дома и углы.",
    addTimeAction: "Добавьте время",
    missingPlaceStatus: "Нужно место рождения",
    missingPlaceDetail: (items: readonly string[]) =>
      `Заполните ${items.join(", ")} в карточке клиента.`,
    fillDataAction: "Заполните данные",
    choosePartnerStatus: "Выберите партнёра",
    synastryNeedsPartner: "Для синастрии нужен второй клиент.",
    compositeNeedsPartner: "Для композита нужен второй клиент.",
    otherPartnerStatus: "Нужен другой партнёр",
    otherPartnerDetail: (method: string) =>
      `Для ${method} выберите второго клиента, не текущую карту.`,
    synastryInstrumental: "синастрии",
    compositeInstrumental: "композита",
    chooseOtherAction: "Выберите другого",
    partnerTimeStatus: "Нужно время партнёра",
    partnerDataStatus: "Нужны данные партнёра",
    partnerMissingDetail: (items: readonly string[]) =>
      `У партнёра не заполнены: ${items.join(", ")}.`,
    fillPartnerAction: "Заполните партнёра",
    horaryChangedStatus: "Хорар изменён",
    horaryCalculatedStatus: "Хорар рассчитан",
    horaryReadyStatus: "Готово к хорару",
    horaryMissingDetail: (items: readonly string[]) => `Заполните: ${items.join(", ")}.`,
    fillHoraryAction: "Заполните хорар"
  },
  status: {
    failed: "Расчёт не выполнен",
    defaultFailure: "Проверьте данные рождения клиента и повторите расчёт.",
    choosePartner: "Выберите партнёра",
    partnerSource: "Выберите второго участника из списка клиентов.",
    partnerData: "Нужны данные партнёра",
    partnerMissing: (items: readonly string[], method: string) =>
      `Добавьте ${items.join(", ")}, чтобы рассчитать ${method}.`,
    stale: "Карта устарела",
    synastryObject: "синастрию",
    compositeObject: "композит"
  },
  birthData: {
    workspaceLabel: "Заполнение данных рождения",
    title: "Заполните данные рождения",
    description: "Сохраним в карточку клиента и сразу разблокируем расчёт натала.",
    defaultLabel: "Основные данные",
    date: "Дата рождения",
    chooseDate: "Выберите дату",
    openCalendar: "Открыть календарь",
    precision: "Точность времени",
    unknown: "Неизвестно",
    approximate: "Примерно",
    exact: "Точно",
    time: "Время рождения",
    timeAria: (value: string) => `Время рождения: ${value || "не выбрано"}`,
    chooseTime: "Выберите время",
    choosePrecisionFirst: "Сначала выберите точность",
    openClock: "Открыть часы",
    place: "Место рождения",
    placePlaceholder: "Москва, Россия",
    searchingPlace: "Ищем место…",
    placeOptions: "Варианты места",
    placeNotFound: "Место не найдено. Уточните запрос или заполните координаты вручную.",
    placeSearchError: "Не удалось найти место. Попробуйте уточнить запрос позже.",
    manualCoordinates: "Ввести координаты вручную",
    timezone: "Часовой пояс",
    latitude: "Широта",
    longitude: "Долгота",
    save: "Сохранить данные рождения",
    saving: "Сохраняем…",
    month: "Месяц",
    birthMonth: "Месяц рождения",
    year: "Год",
    birthYear: "Год рождения",
    hours: "Часы",
    minutes: "Минуты",
    minuteAria: (minute: string) => `${minute} минут`
  },
  calendar: {
    months: [
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь"
    ],
    monthsGenitive: [
      "января",
      "февраля",
      "марта",
      "апреля",
      "мая",
      "июня",
      "июля",
      "августа",
      "сентября",
      "октября",
      "ноября",
      "декабря"
    ],
    weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    dateAria: (day: number, month: string, year: number) => `${day} ${month} ${year}`
  },
  moment: {
    transitDate: "Дата транзита",
    transitTime: "Время транзита",
    solarYear: "Год соляра",
    progressionDate: "Дата прогрессии"
  },
  horary: {
    setupTitle: "Параметры хорара",
    preparationTitle: "Подготовка хорара",
    preparationDetail:
      "Сформулируйте вопрос, зафиксируйте момент и выберите место — карта построится по этим данным.",
    previewTitle: "Предпросмотр карты",
    previewPending: "Ожидает обязательные поля",
    previewEmptyTitle: "Карта появится здесь",
    previewEmptyDetail:
      "Заполните три группы слева. Как только обязательные поля готовы, можно запустить построение хорарной карты.",
    previewQuestionPending: "Заполните вопрос",
    previewMomentReady: "Время зафиксировано",
    previewMomentPending: "Укажите момент",
    previewPlacePending: "Выберите город",
    previewPlaceReady: "Место готово",
    calculateHint: "Заполните вопрос и место, чтобы начать расчёт",
    preparationMoment: "Момент",
    momentTitle: "Момент вопроса",
    question: "Вопрос",
    questionPrompt: "Что именно нужно прояснить?",
    questionHint: "Один конкретный вопрос даёт наиболее ясную карту.",
    questionAria: "Вопрос хорара",
    questionPlaceholder: "Например: Подпишет ли клиент договор в этом месяце?",
    category: "Категория",
    categoryAria: "Категория хорара",
    date: "Дата",
    dateAria: "Дата вопроса",
    time: "Время",
    timeAria: "Время вопроса",
    timezone: "TZ",
    timezoneAria: "Часовой пояс вопроса",
    latitude: "Широта",
    latitudeAria: "Широта вопроса",
    longitude: "Долгота",
    longitudeAria: "Долгота вопроса",
    place: "Место вопроса",
    previewPlaceLabel: "Место",
    placeGroup: "Место и координаты",
    manualCoordinates: "Уточнить координаты вручную",
    placeAria: "Место вопроса",
    placePlaceholder: "Найдите город или место",
    placeSearching: "Ищем место…",
    placeOptions: "Варианты места вопроса",
    placeSelected: (label: string) => `Выбрано: ${label}`,
    placeInvalid: "Ссылка на место вопроса недействительна. Выберите место заново",
    placeNotFound: "Место вопроса больше не найдено. Выберите место заново",
    placeRateLimited: "Сервис мест временно ограничил запросы. Повторите позже",
    placeUnavailable: "Не удалось восстановить место вопроса. Повторите позже",
    categories: {
      relationship: "Отношения",
      career: "Работа",
      money: "Деньги",
      home: "Дом",
      health: "Здоровье",
      travel: "Поездка",
      other: "Другое"
    }
  },
  tables: {
    emptyInterpretations: "После расчёта здесь появятся трактовки.",
    emptyTables: "После расчёта здесь появятся планеты, аспекты и дома.",
    planets: "Планеты",
    transitPlanets: "Транзитные планеты",
    solarPlanets: "Планеты соляра",
    progressedPlanets: "Прогрессивные планеты",
    partnerPlanets: "Планеты партнёра",
    house: (roman: string) => `${roman} дом`,
    houses: "Дома",
    aspects: "Аспекты",
    aspectMatrix: "Матрица аспектов",
    insufficientMatrix: "Недостаточно точек для матрицы",
    aspectLegend: "Легенда аспектов",
    aspectList: "Список аспектов",
    noMajorAspects: "Мажорные аспекты не найдены",
    transitAspects: "Транзитные аспекты к наталу",
    noTransitAspects: "Транзитные аспекты к наталу не найдены",
    solarAspects: "Солярные аспекты к наталу",
    noSolarAspects: "Солярные аспекты к наталу не найдены",
    progressionAspects: "Прогрессивные аспекты к наталу",
    noProgressionAspects: "Прогрессивные аспекты к наталу не найдены",
    betweenAspects: "Аспекты между картами",
    noBetweenAspects: "Аспекты между картами не найдены",
    orb: "орбис",
    interpretations: "Трактовки",
    interpretationKickers: {
      child: "Детские трактовки · библиотека",
      horary: "Хорар · библиотека",
      astrocartography: "Астрокартография · библиотека",
      default: "Опорные положения · библиотека"
    },
    groupTitles: { points: "Положения", houses: "Дома", aspects: "Аспекты" },
    dictionaryLoadError: "Не удалось загрузить трактовки из справочника.",
    dictionaryLoading: "Загружаем трактовку из справочника...",
    dictionaryMissing: "Для этого элемента еще нет трактовки",
    dictionarySource: (source: string) => `Справочник · ${source}`,
    addInterpretation: "Добавить трактовку",
    addInterpretationAria: (title: string) => `Добавить трактовку для ${title}`,
    interpretationEditor: {
      ariaLabel: (title: string) => `Новая трактовка: ${title}`,
      backAriaLabel: "Вернуться к трактовкам",
      kicker: "Новая трактовка",
      description: "Заполните свою трактовку для выбранного элемента карты.",
      categoriesLoading: "Подготавливаем форму...",
      categoriesError: "Не удалось подготовить форму. Повторите попытку.",
      categoryLabel: "Категория",
      titleLabel: "Название",
      contentLabel: "Текст трактовки",
      contentPlaceholder: "Ваша трактовка...",
      cancel: "Отмена",
      save: "Сохранить",
      saving: "Сохраняем...",
      saveError: "Не удалось сохранить трактовку. Повторите попытку."
    }
  },
  interpretationAnchors: {
    house: (roman: string) => `${roman} дом`,
    pointInSign: (point: string, sign: string) => `${point} в ${sign}`,
    pointInHouse: (point: string, house: string) => `${point} · ${house}`,
    orb: (aspect: string, orb: string) => `${aspect} · орбис ${orb}°`,
    childPointSign: "Детская карта · планета в знаке",
    childPointHouse: "Детская карта · планета в доме",
    childHouse: "Детская карта · значение дома",
    childAspect: "Детская карта · аспект",
    compositePointSign: "Композит · планета в знаке",
    compositePointHouse: "Композит · планета в доме",
    compositeHouse: "Композит · значение дома",
    compositeAspect: "Композит · аспект",
    horaryCategory: "Категория вопроса",
    horaryCategoryMeta: "Хорар · категория вопроса",
    horaryPointSign: "Хорар · планета в знаке",
    horaryPointHouse: "Хорар · планета в доме",
    horaryHouse: "Хорар · значение дома",
    horaryAspect: "Хорар · аспект",
    astroLine: "Астрокартография · линия планеты",
    pointsCount: (count: number) => `${count} точек`,
    pointSign: "Планета в знаке",
    pointHouse: "Планета в доме",
    houseMeaning: "Значение дома",
    transitLabel: (point: string, natal: string) => `Транзитный ${point} — ${natal}`,
    transitMeta: "Транзит к наталу",
    solarLabel: (point: string, natal: string) => `Солярный ${point} — ${natal}`,
    solarMeta: "Соляр к наталу",
    progressionLabel: (point: string, natal: string) => `Прогрессивный ${point} — ${natal}`,
    progressionMeta: "Прогрессия к наталу",
    partnerSuffix: "партнёра",
    primaryOwner: "клиента",
    partnerOwner: "партнёра",
    synastryAspect: "Синастрический аспект",
    synastryOverlay: "Синастрическое наложение",
    compatibilityScore: "Оценка совместимости",
    synastrySummary: "Синастрический итог",
    aspectType: "Тип аспекта",
    aspectPattern: "Общий паттерн аспекта",
    planetConnection: "Связь планет"
  },
  map: {
    ariaLabel: "Астрокартографическая карта",
    legendLabel: "Легенда астрокартографии",
    linesLabel: "Линии астрокартографии",
    lineDescription: (point: string, angle: string, label: string) => `${point}, ${angle}: ${label}`
  },
  wheel: {
    stageLabel: "Натальная карта",
    wheelLabel: "Круг карты",
    invalidResult: "Результат карты повреждён: отсутствует первый дом",
    pointOnChart: (point: string) => `${point} на карте`,
    transitPointOnChart: (point: string) => `Транзитный ${point} на карте`,
    solarPointOnChart: (point: string) => `Солярный ${point} на карте`,
    progressedPointOnChart: (point: string) => `Прогрессивный ${point} на карте`,
    partnerPointOnChart: (point: string) => `Партнёрский ${point} на карте`,
    hint: "Наведите на планету — детали, дом и аспекты",
    transitPrefix: "Транзитный ",
    solarPrefix: "Солярный ",
    progressedPrefix: "Прогрессивный ",
    partnerPrefix: "Партнёрский ",
    retrograde: " R ретроград",
    selectedAspects: "Аспекты выбранной планеты",
    noAspects: "нет аспектов"
  },
  settings: {
    ariaLabel: "Настройки расчёта",
    houseSystem: "Система домов",
    houseSystems: {
      placidus: "Плацидус",
      koch: "Кох",
      whole_sign: "Цельнознаковая",
      equal: "Равнодомная",
      regiomontanus: "Региомонтан"
    },
    nodes: "Лунные узлы",
    trueNode: "Истинный узел",
    meanNode: "Средний узел",
    aspects: "Аспекты",
    major: "Только мажорные",
    majorMinor: "Мажорные + минорные",
    orbs: "Орбисы",
    orbHelper: "Шире орбис — больше аспектов на колесе. Меняет расчёт для следующего запуска.",
    presetNote: "Пресет применяется ко всем новым картам автоматически."
  },
  ai: {
    heading: "Черновик трактовки",
    description:
      "Сгенерируйте текст поверх результата расчёта, проверьте и утвердите перед клиентом.",
    approved: "утверждено",
    draft: "черновик",
    generating: "Генерируем...",
    regenerate: "Сгенерировать заново",
    generate: "Сгенерировать",
    saving: "Сохраняем...",
    save: "Сохранить правки",
    approving: "Утверждаем...",
    approve: "Утвердить",
    loadingPlaceholder: "Загружаем черновик...",
    placeholder: "AI-черновик появится здесь.",
    noResult: "После расчёта натальной карты здесь появится AI-черновик.",
    stale: "Результат устарел. Пересчитайте карту перед AI-черновиком.",
    saveCalculation: "Сначала сохраните расчёт карты.",
    unsupported: "AI-черновик пока доступен только для натальной карты.",
    loadError: "Не удалось загрузить расчёт карты. Обновите страницу и повторите",
    saveError: "Не удалось сохранить черновик",
    approveError: "Не удалось утвердить трактовку",
    conflict: "Расчёт изменился. Откройте его заново и повторите генерацию",
    invalid: "AI не смог создать черновик для этих данных. Проверьте расчёт и повторите",
    limit: "Лимит AI-генераций исчерпан. Повторите позже",
    malformed: "AI вернул некорректный черновик. Повторите генерацию",
    unavailable: "AI временно недоступен. Повторите позже",
    generic: "Не удалось создать AI-черновик",
    manualConflict:
      "Этот ключ повтора уже использован для другого текста. Измените текст и повторите",
    resultChanged: "Расчёт изменился. Откройте его заново и повторите сохранение",
    storageUnavailable: "Хранилище трактовок временно недоступно. Повторите с тем же текстом"
  },
  pdf: {
    calculateFirst: "Сначала рассчитайте карту",
    recalculateFirst: "Сначала пересчитайте карту",
    loading: "Загружаем состояние PDF",
    preparing: "PDF готовится…",
    forming: "PDF формируется",
    download: "Скачать PDF",
    downloadTitle: "Скачать готовый PDF",
    retry: "Повторить",
    retryTitle: "Повторить формирование PDF",
    failed: (reason: string) => `Не удалось сформировать PDF: ${reason}`,
    failedDefault: "Не удалось сформировать PDF. Повторите попытку.",
    form: "Сформировать PDF",
    changed: "Карта изменилась. Пересчитайте её и сформируйте PDF заново",
    unavailable: "PDF-экспорт карты временно недоступен. Повторите позже",
    genericError: "Не удалось выполнить действие с PDF. Повторите позже"
  },
  missing: {
    birthDate: "дата рождения",
    birthTime: "время рождения",
    timezone: "часовой пояс",
    coordinates: "координаты места рождения",
    question: "вопрос",
    questionDate: "дата вопроса",
    questionTime: "время вопроса",
    questionLatitude: "широта вопроса",
    questionLongitude: "долгота вопроса"
  },
  controller: {
    identityWrongClient: "Сохранённый расчёт относится к другому клиенту",
    identityWrongPartner: "Сохранённый расчёт относится к другому партнёру",
    identityUnavailable: "Сохранённый расчёт недоступен или не соответствует выбранному режиму",
    cannotRecalculate: "Сохранённый расчёт нельзя пересчитать в текущем состоянии",
    cannotConfirmVersion: "Не удалось подтвердить версию сохранённого расчёта",
    wrongJobTarget: "Статус задания не соответствует исходному расчёту",
    startFailed: "Не удалось запустить расчёт карты",
    recalculationChanged: "Сохранённый расчёт изменился после запуска задания",
    calculationFailed: "Не удалось рассчитать карту",
    pdfFailed: "Не удалось выполнить PDF-действие",
    chooseClient: "Выберите клиента",
    missingBirthData: (items: readonly string[]) =>
      `Не хватает данных рождения: ${items.join(", ")}`,
    transitMoment: "Укажите дату и время транзита",
    choosePartner: "Выберите партнёра",
    synastryOtherClient: "Для синастрии выберите другого клиента",
    compositeOtherClient: "Для композита выберите другого клиента",
    missingPartnerBirthData: (items: readonly string[]) =>
      `Не хватает данных рождения партнёра: ${items.join(", ")}`,
    progressionDate: "Укажите дату прогрессии",
    fillHorary: "Заполните хорар",
    timezoneUnavailable: "Не удалось определить часовой пояс браузера. Укажите его вручную"
  }
} as const;

type Widen<T> = T extends (...args: infer Args) => infer Result
  ? (...args: Args) => Result
  : T extends string
    ? string
    : T extends number
      ? number
      : T extends readonly (infer Item)[]
        ? readonly Widen<Item>[]
        : T extends object
          ? { readonly [Key in keyof T]: Widen<T[Key]> }
          : T;

export type ChartEngineCopy = Widen<typeof ruChartEngineCopy>;

const enModes: ChartEngineCopy["modes"] = {
  natal: {
    tab: "Natal",
    title: "Natal chart",
    calculating: "Calculating chart",
    calculationDetail: "Building a chart from the client's birth data.",
    emptyTitle: "Ready to calculate natal chart",
    emptyDetail:
      "Choose a client with a complete birth date, time, timezone, and birth coordinates.",
    readyDetail: "Birth data and settings are ready for a natal chart.",
    successDetail: "The natal chart has been calculated and linked to the client.",
    staleDetail:
      "Birth data or settings changed. Recalculate the natal chart to refresh the wheel and tables.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate"
  },
  child_chart: {
    tab: "Child",
    title: "Child chart",
    calculating: "Calculating child chart",
    calculationDetail: "Building a chart with child-friendly interpretations.",
    emptyTitle: "Ready to calculate child chart",
    emptyDetail: "Choose a client to build the chart and open child-friendly interpretations.",
    readyDetail: "Everything is ready to build the chart and open child-friendly interpretations.",
    successDetail:
      "The calculation uses natal placements with interpretations adapted for a parent-facing reading.",
    staleDetail: "Birth data or settings changed. Recalculate the child chart.",
    staleAction: "Recalculate child chart",
    calculateAction: "Calculate child chart"
  },
  transit: {
    tab: "Transits",
    title: "Transit chart",
    calculating: "Calculating transits",
    calculationDetail: "Building transits from the client's birth data and the selected moment.",
    emptyTitle: "Ready to calculate transits",
    emptyDetail: "Choose a client and enter the transit date, time, and place.",
    readyDetail: "The client's natal chart and transit moment are ready.",
    successDetail: "Transits were calculated for the client's natal chart and selected moment.",
    staleDetail: "Birth data, settings, or the transit moment changed. Recalculate the chart.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate transits"
  },
  progression: {
    tab: "Progressions",
    title: "Progressions",
    calculating: "Calculating progressions",
    calculationDetail: "Building secondary progressions for the selected date.",
    emptyTitle: "Ready to calculate progressions",
    emptyDetail: "Choose a client and progression date.",
    readyDetail: "The client's natal chart and progression date are ready.",
    successDetail: "Progressions were calculated for the client's natal chart and selected date.",
    staleDetail: "Birth data, settings, or the progression date changed. Recalculate progressions.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate progressions"
  },
  synastry: {
    tab: "Synastry",
    title: "Synastry",
    calculating: "Calculating synastry",
    calculationDetail: "Building a compatibility chart from both clients' birth data.",
    emptyTitle: "Ready to calculate synastry",
    emptyDetail: "Choose a second client for a compatibility chart.",
    readyDetail: "Both clients are ready for a compatibility calculation.",
    successDetail: "Synastry was calculated for the selected client pair.",
    staleDetail: "A participant's data or settings changed. Recalculate synastry.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate synastry"
  },
  composite: {
    tab: "Composite",
    title: "Composite",
    calculating: "Calculating composite",
    calculationDetail: "Building a shared relationship chart from both clients' birth data.",
    emptyTitle: "Ready to calculate composite",
    emptyDetail: "Choose a second client to build the relationship chart.",
    readyDetail: "Both clients are ready for a composite chart.",
    successDetail: "The composite was calculated as one relationship wheel for the selected pair.",
    staleDetail: "A participant's data or settings changed. Recalculate the composite.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate composite"
  },
  solar_return: {
    tab: "Solar return",
    title: "Solar return",
    calculating: "Calculating solar return",
    calculationDetail: "Building a solar return for the selected year.",
    emptyTitle: "Ready to calculate solar return",
    emptyDetail: "Choose a client and solar-return year.",
    readyDetail: "The client's natal chart and solar-return year are ready.",
    successDetail:
      "The solar return was calculated for the client's natal chart and selected year.",
    staleDetail: "Birth data, settings, or the solar-return year changed. Recalculate it.",
    staleAction: "Recalculate chart",
    calculateAction: "Calculate solar return"
  },
  astrocartography: {
    tab: "Astrocartography",
    title: "Astrocartography",
    calculating: "Calculating lines",
    calculationDetail: "Building planetary lines on the world map from the client's birth data.",
    emptyTitle: "Ready to calculate astrocartography",
    emptyDetail: "Choose a client to build planetary lines on the world map.",
    readyDetail: "The client's natal chart is ready for world-map line calculation.",
    successDetail: "Planetary lines were calculated from the client's natal chart.",
    staleDetail: "Birth data or settings changed. Recalculate the world-map lines.",
    staleAction: "Recalculate lines",
    calculateAction: "Calculate lines"
  },
  horary: {
    tab: "Horary",
    title: "Horary",
    calculating: "Calculating horary chart",
    calculationDetail: "Building a chart for the question moment; client birth data is not used.",
    emptyTitle: "Ready for horary",
    emptyDetail: "Choose a client and enter the question, moment, and place.",
    readyDetail: "Enter a question and moment to build the question chart.",
    successDetail: "The chart was built for the question moment; no automated answer is enabled.",
    staleDetail: "The question, moment, place, or settings changed. Recalculate the chart.",
    staleAction: "Recalculate horary",
    calculateAction: "Calculate horary"
  }
};

const enChartEngineCopy: ChartEngineCopy = {
  ...ruChartEngineCopy,
  documentTitle: "ElevenHouse | Chart Engine",
  title: "Chart Engine",
  modes: enModes,
  modeMenu: {
    navigationLabel: "Chart type",
    openLabel: "Open other chart types",
    menuLabel: "Other chart types"
  },
  client: {
    label: "Client",
    choose: "Choose a client",
    fallbackInitial: "C",
    crmSource: "Birth date not set",
    partnerLabel: "Partner",
    choosePartner: "Choose a partner",
    partnerFallbackInitial: "P",
    partnerPrefix: "Partner"
  },
  actionBar: {
    exportLabel: "Export chart",
    exportUnavailable: "Chart export is not available yet",
    link: "Link",
    linked: "✓ Linked",
    linkUnavailable: "Calculate the chart before linking it to the client",
    birthData: "Birth data",
    settings: "Settings",
    childPdfUnavailable: "Child chart PDF is not available yet",
    horaryPdfUnavailable: "Horary PDF is not available yet",
    methodPdfUnavailable: "PDF is not available yet for this chart type",
    defaultPdfUnavailable: "PDF is available after chart calculation"
  },
  recovery: {
    regionLabel: "Chart data recovery",
    retryPoll: "Retry chart status check",
    retryResult: "Retry result loading",
    retrySaved: "Retry saved calculation loading",
    retryLink: "Retry linking",
    recoverIdentity: "Open calculation clients"
  },
  emptyClient: {
    title: "Choose a client",
    description: "The chart appears after choosing a client."
  },
  rail: {
    ariaLabel: "Chart summary",
    birthData: "Birth data",
    missing: (items) => `Missing: ${items.join(", ")}.`,
    warnings: "Warnings",
    approximateWarning: "Birth time is approximate; houses and angles may shift.",
    astrocartography: "Astrocartography",
    bigThree: "Big three",
    linesPending: "Appears after line calculation.",
    chartPending: "Appears after calculation.",
    retrogrades: "Retrograde",
    noRetrogrades: "None in the current result.",
    elements: "Elements",
    modalities: "Modalities",
    polarity: "Polarity",
    dominants: "Dominants",
    aspectsShort: "asp.",
    insufficientAspects: "Not enough aspects.",
    astroLines: "Lines",
    astroPlanets: "Planets",
    astroAngles: "Angles",
    sun: "Sun",
    moon: "Moon"
  },
  distributions: {
    elements: { fire: "Fire", earth: "Earth", air: "Air", water: "Water" },
    modalities: { cardinal: "Cardinal", fixed: "Fixed", mutable: "Mutable" },
    polarity: { masculine: "Masculine", feminine: "Feminine" }
  },
  panel: {
    ariaLabel: "Chart data",
    settingsTitle: "Calculation settings",
    closeSettings: "Close calculation settings",
    tabs: {
      planets: "Planets",
      aspects: "Aspects",
      houses: "Houses",
      interpretations: "Interpretations",
      ai: "AI"
    }
  },
  view: {
    selectClientStatus: "Choose a client",
    selectClientDetail: "Choose a client to build a chart.",
    calculatingStatus: "Calculation in progress",
    calculatingDetail: "Preparing the chart.",
    calculatingAction: "Calculating",
    failedStatus: "Calculation error",
    failedDetail: "Check the client's birth data and retry the calculation.",
    retryCalculation: "Retry calculation",
    staleStatus: "Recalculation required",
    currentStatus: "Current chart",
    currentAction: "Current",
    readyStatus: "Ready to calculate",
    approximateStatus: "Approximate time",
    approximateDetail:
      "Calculation is available, but the chart will include a time-accuracy warning.",
    approximateAction: "Calculate with warning",
    missingDateStatus: "Birth date required",
    missingDateDetail: "Add the birth date to the client record.",
    addDateAction: "Add date",
    missingTimeStatus: "Birth time required",
    missingTimeDetail: "Houses and angles cannot be calculated without a birth time.",
    addTimeAction: "Add time",
    missingPlaceStatus: "Birth place required",
    missingPlaceDetail: (items) => `Add ${items.join(", ")} to the client record.`,
    fillDataAction: "Complete data",
    choosePartnerStatus: "Choose a partner",
    synastryNeedsPartner: "Synastry requires a second client.",
    compositeNeedsPartner: "Composite requires a second client.",
    otherPartnerStatus: "Choose another partner",
    otherPartnerDetail: (method) => `For ${method}, choose a second client, not the current chart.`,
    synastryInstrumental: "synastry",
    compositeInstrumental: "composite",
    chooseOtherAction: "Choose another",
    partnerTimeStatus: "Partner birth time required",
    partnerDataStatus: "Partner birth data required",
    partnerMissingDetail: (items) => `The partner is missing: ${items.join(", ")}.`,
    fillPartnerAction: "Complete partner data",
    horaryChangedStatus: "Horary data changed",
    horaryCalculatedStatus: "Horary chart calculated",
    horaryReadyStatus: "Ready for horary",
    horaryMissingDetail: (items) => `Complete: ${items.join(", ")}.`,
    fillHoraryAction: "Complete horary data"
  },
  status: {
    failed: "Calculation failed",
    defaultFailure: "Check the client's birth data and retry the calculation.",
    choosePartner: "Choose a partner",
    partnerSource: "Choose the second participant from your client list.",
    partnerData: "Partner data required",
    partnerMissing: (items, method) => `Add ${items.join(", ")} to calculate ${method}.`,
    stale: "Chart is outdated",
    synastryObject: "synastry",
    compositeObject: "composite"
  },
  birthData: {
    workspaceLabel: "Enter birth data",
    title: "Complete birth data",
    description: "It will be saved to the client record and immediately unlock natal calculation.",
    defaultLabel: "Primary data",
    date: "Birth date",
    chooseDate: "Choose a date",
    openCalendar: "Open calendar",
    precision: "Time precision",
    unknown: "Unknown",
    approximate: "Approximate",
    exact: "Exact",
    time: "Birth time",
    timeAria: (value) => `Birth time: ${value || "not selected"}`,
    chooseTime: "Choose a time",
    choosePrecisionFirst: "Choose time precision first",
    openClock: "Open time picker",
    place: "Birth place",
    placePlaceholder: "London, United Kingdom",
    searchingPlace: "Searching for a place…",
    placeOptions: "Place options",
    placeNotFound: "Place not found. Refine the query or enter coordinates manually.",
    placeSearchError: "Could not find the place. Refine the query and try again later.",
    manualCoordinates: "Enter coordinates manually",
    timezone: "Timezone",
    latitude: "Latitude",
    longitude: "Longitude",
    save: "Save birth data",
    saving: "Saving…",
    month: "Month",
    birthMonth: "Birth month",
    year: "Year",
    birthYear: "Birth year",
    hours: "Hours",
    minutes: "Minutes",
    minuteAria: (minute) => `${minute} minutes`
  },
  calendar: {
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ],
    monthsGenitive: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December"
    ],
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    dateAria: (day, month, year) => `${month} ${day}, ${year}`
  },
  moment: {
    transitDate: "Transit date",
    transitTime: "Transit time",
    solarYear: "Solar-return year",
    progressionDate: "Progression date"
  },
  horary: {
    setupTitle: "Horary parameters",
    preparationTitle: "Preparing horary",
    preparationDetail:
      "Formulate the question, set the moment, and choose the place — the chart will use these details.",
    previewTitle: "Chart preview",
    previewPending: "Waiting for required fields",
    previewEmptyTitle: "The chart will appear here",
    previewEmptyDetail:
      "Fill in the three groups on the left. Once the required fields are ready, you can start the horary calculation.",
    previewQuestionPending: "Enter the question",
    previewMomentReady: "Moment is set",
    previewMomentPending: "Set the moment",
    previewPlacePending: "Choose a city",
    previewPlaceReady: "Place is ready",
    calculateHint: "Enter the question and place to start the calculation",
    preparationMoment: "Moment",
    momentTitle: "Question moment",
    question: "Question",
    questionPrompt: "What needs clarification?",
    questionHint: "One specific question produces the clearest chart.",
    questionAria: "Horary question",
    questionPlaceholder: "For example: Will the client sign the contract this month?",
    category: "Category",
    categoryAria: "Horary category",
    date: "Date",
    dateAria: "Question date",
    time: "Time",
    timeAria: "Question time",
    timezone: "TZ",
    timezoneAria: "Question timezone",
    latitude: "Latitude",
    latitudeAria: "Question latitude",
    longitude: "Longitude",
    longitudeAria: "Question longitude",
    place: "Question place",
    previewPlaceLabel: "Place",
    placeGroup: "Place and coordinates",
    manualCoordinates: "Refine coordinates manually",
    placeAria: "Question place",
    placePlaceholder: "Search for a city or place",
    placeSearching: "Searching for a place…",
    placeOptions: "Question place options",
    placeSelected: (label) => `Selected: ${label}`,
    placeInvalid: "The question place reference is invalid. Choose the place again",
    placeNotFound: "The question place is no longer available. Choose it again",
    placeRateLimited: "The place service has temporarily limited requests. Try again later",
    placeUnavailable: "Could not restore the question place. Try again later",
    categories: {
      relationship: "Relationships",
      career: "Career",
      money: "Money",
      home: "Home",
      health: "Health",
      travel: "Travel",
      other: "Other"
    }
  },
  tables: {
    emptyInterpretations: "Interpretations appear here after calculation.",
    emptyTables: "Planets, aspects, and houses appear here after calculation.",
    planets: "Planets",
    transitPlanets: "Transit planets",
    solarPlanets: "Solar-return planets",
    progressedPlanets: "Progressed planets",
    partnerPlanets: "Partner planets",
    house: (roman) => `${roman} house`,
    houses: "Houses",
    aspects: "Aspects",
    aspectMatrix: "Aspect matrix",
    insufficientMatrix: "Not enough points for the matrix",
    aspectLegend: "Aspect legend",
    aspectList: "Aspect list",
    noMajorAspects: "No major aspects found",
    transitAspects: "Transit aspects to natal",
    noTransitAspects: "No transit aspects to natal found",
    solarAspects: "Solar-return aspects to natal",
    noSolarAspects: "No solar-return aspects to natal found",
    progressionAspects: "Progressed aspects to natal",
    noProgressionAspects: "No progressed aspects to natal found",
    betweenAspects: "Aspects between charts",
    noBetweenAspects: "No aspects between charts found",
    orb: "orb",
    interpretations: "Interpretations",
    interpretationKickers: {
      child: "Child interpretations · library",
      horary: "Horary · library",
      astrocartography: "Astrocartography · library",
      default: "Key placements · library"
    },
    groupTitles: { points: "Placements", houses: "Houses", aspects: "Aspects" },
    dictionaryLoadError: "Could not load interpretations from the reference library.",
    dictionaryLoading: "Loading interpretation from the reference library...",
    dictionaryMissing: "There is no interpretation for this item yet.",
    dictionarySource: (source) => `Reference · ${source}`,
    addInterpretation: "Add interpretation",
    addInterpretationAria: (title) => `Add interpretation for ${title}`,
    interpretationEditor: {
      ariaLabel: (title) => `New interpretation: ${title}`,
      backAriaLabel: "Return to interpretations",
      kicker: "New interpretation",
      description: "Write your interpretation for the selected chart item.",
      categoriesLoading: "Preparing the form...",
      categoriesError: "Could not prepare the form. Try again.",
      categoryLabel: "Category",
      titleLabel: "Title",
      contentLabel: "Interpretation text",
      contentPlaceholder: "Your interpretation...",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving...",
      saveError: "Could not save the interpretation. Try again."
    }
  },
  interpretationAnchors: {
    house: (roman) => `${roman} house`,
    pointInSign: (point, sign) => `${point} in ${sign}`,
    pointInHouse: (point, house) => `${point} · ${house}`,
    orb: (aspect, orb) => `${aspect} · orb ${orb}°`,
    childPointSign: "Child chart · planet in sign",
    childPointHouse: "Child chart · planet in house",
    childHouse: "Child chart · house meaning",
    childAspect: "Child chart · aspect",
    compositePointSign: "Composite · planet in sign",
    compositePointHouse: "Composite · planet in house",
    compositeHouse: "Composite · house meaning",
    compositeAspect: "Composite · aspect",
    horaryCategory: "Question category",
    horaryCategoryMeta: "Horary · question category",
    horaryPointSign: "Horary · planet in sign",
    horaryPointHouse: "Horary · planet in house",
    horaryHouse: "Horary · house meaning",
    horaryAspect: "Horary · aspect",
    astroLine: "Astrocartography · planetary line",
    pointsCount: (count) => `${count} points`,
    pointSign: "Planet in sign",
    pointHouse: "Planet in house",
    houseMeaning: "House meaning",
    transitLabel: (point, natal) => `Transit ${point} — ${natal}`,
    transitMeta: "Transit to natal",
    solarLabel: (point, natal) => `Solar-return ${point} — ${natal}`,
    solarMeta: "Solar return to natal",
    progressionLabel: (point, natal) => `Progressed ${point} — ${natal}`,
    progressionMeta: "Progression to natal",
    partnerSuffix: "partner",
    primaryOwner: "client",
    partnerOwner: "partner",
    synastryAspect: "Synastry aspect",
    synastryOverlay: "Synastry overlay",
    compatibilityScore: "Compatibility score",
    synastrySummary: "Synastry summary",
    aspectType: "Aspect type",
    aspectPattern: "General aspect pattern",
    planetConnection: "Planet connection"
  },
  map: {
    ariaLabel: "Astrocartography map",
    legendLabel: "Astrocartography legend",
    linesLabel: "Astrocartography lines",
    lineDescription: (point, angle, label) => `${point}, ${angle}: ${label}`
  },
  wheel: {
    stageLabel: "Natal chart",
    wheelLabel: "Chart wheel",
    invalidResult: "The chart result is invalid: the first house is missing",
    pointOnChart: (point) => `${point} on chart`,
    transitPointOnChart: (point) => `Transit ${point} on chart`,
    solarPointOnChart: (point) => `Solar-return ${point} on chart`,
    progressedPointOnChart: (point) => `Progressed ${point} on chart`,
    partnerPointOnChart: (point) => `Partner ${point} on chart`,
    hint: "Hover a planet for details, house, and aspects",
    transitPrefix: "Transit ",
    solarPrefix: "Solar-return ",
    progressedPrefix: "Progressed ",
    partnerPrefix: "Partner ",
    retrograde: " R retrograde",
    selectedAspects: "Selected planet aspects",
    noAspects: "no aspects"
  },
  settings: {
    ariaLabel: "Calculation settings",
    houseSystem: "House system",
    houseSystems: {
      placidus: "Placidus",
      koch: "Koch",
      whole_sign: "Whole sign",
      equal: "Equal house",
      regiomontanus: "Regiomontanus"
    },
    nodes: "Lunar nodes",
    trueNode: "True node",
    meanNode: "Mean node",
    aspects: "Aspects",
    major: "Major only",
    majorMinor: "Major + minor",
    orbs: "Orbs",
    orbHelper: "A wider orb shows more aspects on the wheel and changes the next calculation.",
    presetNote: "The preset is automatically applied to every new chart."
  },
  ai: {
    heading: "Interpretation draft",
    description:
      "Generate text from the calculation result, review it, and approve it before sharing.",
    approved: "approved",
    draft: "draft",
    generating: "Generating...",
    regenerate: "Generate again",
    generate: "Generate",
    saving: "Saving...",
    save: "Save changes",
    approving: "Approving...",
    approve: "Approve",
    loadingPlaceholder: "Loading draft...",
    placeholder: "The AI draft appears here.",
    noResult: "An AI draft appears here after a natal chart calculation.",
    stale: "The result is outdated. Recalculate the chart before generating an AI draft.",
    saveCalculation: "Save the chart calculation first.",
    unsupported: "AI drafts are currently available for natal charts only.",
    loadError: "Could not load the chart calculation. Refresh the page and try again",
    saveError: "Could not save the draft",
    approveError: "Could not approve the interpretation",
    conflict: "The calculation changed. Open it again and retry generation",
    invalid: "AI could not create a draft for this data. Check the calculation and try again",
    limit: "The AI generation limit has been reached. Try again later",
    malformed: "AI returned an invalid draft. Retry generation",
    unavailable: "AI is temporarily unavailable. Try again later",
    generic: "Could not create the AI draft",
    manualConflict:
      "This retry key was already used for different text. Edit the text and try again",
    resultChanged: "The calculation changed. Open it again and retry saving",
    storageUnavailable:
      "Interpretation storage is temporarily unavailable. Retry with the same text"
  },
  pdf: {
    calculateFirst: "Calculate the chart first",
    recalculateFirst: "Recalculate the chart first",
    loading: "Loading PDF status",
    preparing: "Preparing PDF…",
    forming: "PDF is being generated",
    download: "Download PDF",
    downloadTitle: "Download ready PDF",
    retry: "Retry",
    retryTitle: "Retry PDF generation",
    failed: (reason) => `Could not generate PDF: ${reason}`,
    failedDefault: "Could not generate PDF. Try again.",
    form: "Generate PDF",
    changed: "The chart changed. Recalculate it and generate a new PDF",
    unavailable: "Chart PDF export is temporarily unavailable. Try again later",
    genericError: "Could not complete the PDF action. Try again later"
  },
  missing: {
    birthDate: "birth date",
    birthTime: "birth time",
    timezone: "timezone",
    coordinates: "birth place coordinates",
    question: "question",
    questionDate: "question date",
    questionTime: "question time",
    questionLatitude: "question latitude",
    questionLongitude: "question longitude"
  },
  controller: {
    identityWrongClient: "The saved calculation belongs to another client",
    identityWrongPartner: "The saved calculation belongs to another partner",
    identityUnavailable: "The saved calculation is unavailable or does not match the selected mode",
    cannotRecalculate: "The saved calculation cannot be recalculated in its current state",
    cannotConfirmVersion: "Could not confirm the saved calculation version",
    wrongJobTarget: "The job status does not match the original calculation",
    startFailed: "Could not start chart calculation",
    recalculationChanged: "The saved calculation changed after the job started",
    calculationFailed: "Could not calculate the chart",
    pdfFailed: "Could not complete the PDF action",
    chooseClient: "Choose a client",
    missingBirthData: (items) => `Missing birth data: ${items.join(", ")}`,
    transitMoment: "Enter the transit date and time",
    choosePartner: "Choose a partner",
    synastryOtherClient: "Choose another client for synastry",
    compositeOtherClient: "Choose another client for composite",
    missingPartnerBirthData: (items) => `Missing partner birth data: ${items.join(", ")}`,
    progressionDate: "Enter the progression date",
    fillHorary: "Complete horary data",
    timezoneUnavailable: "The browser timezone could not be determined. Enter it manually"
  }
};

export const chartEngineCopyByLocale = {
  ru: ruChartEngineCopy,
  en: enChartEngineCopy
} satisfies Record<DictionaryLocale, ChartEngineCopy>;

export function getChartEngineCopy(locale: DictionaryLocale): ChartEngineCopy {
  return chartEngineCopyByLocale[locale];
}
