export const ASTROLOGER_FINANCE_UNIT_OF_WORK = Symbol("ASTROLOGER_FINANCE_UNIT_OF_WORK");
export const ASTROLOGER_FINANCE_OPTIONS = Symbol("ASTROLOGER_FINANCE_OPTIONS");
export const ASTROLOGER_PAYOUT_DESTINATION_VAULT = Symbol("ASTROLOGER_PAYOUT_DESTINATION_VAULT");
