export const BOOKING_COMMAND_STORE = Symbol("BOOKING_COMMAND_STORE");
export const BOOKING_CLIENT_READER = Symbol("BOOKING_CLIENT_READER");
export const BOOKING_PRODUCT_READER = Symbol("BOOKING_PRODUCT_READER");
