export const FLOW_STORE = Symbol("FLOW_STORE");
export const FLOW_DEFINITION_CONTROL_STORE = Symbol("FLOW_DEFINITION_CONTROL_STORE");
export const FLOW_DEFINITION_QUERY_STORE = Symbol("FLOW_DEFINITION_QUERY_STORE");
export const FLOW_RUNTIME_STORE = Symbol("FLOW_RUNTIME_STORE");
