export const CLIENT_STORE = Symbol("CLIENT_STORE");
export const CLIENT_CRM_READ_STORE = Symbol("CLIENT_CRM_READ_STORE");
export const CLIENT_BOOKING_SERVICE_WORK_READER = Symbol("CLIENT_BOOKING_SERVICE_WORK_READER");
export const CLIENT_SESSION_SERVICE_WORK_READER = Symbol("CLIENT_SESSION_SERVICE_WORK_READER");
export const BIRTH_PLACE_SEARCH_PROVIDER = Symbol("BIRTH_PLACE_SEARCH_PROVIDER");
