export const CLIENT_STORE = Symbol("CLIENT_STORE");
export const CLIENT_CRM_READ_STORE = Symbol("CLIENT_CRM_READ_STORE");
export const BIRTH_PLACE_SEARCH_PROVIDER = Symbol("BIRTH_PLACE_SEARCH_PROVIDER");
