export const ADMIN_SAVED_CARD_DISCLOSURE_CLOCK = Symbol("ADMIN_SAVED_CARD_DISCLOSURE_CLOCK");
export const ADMIN_SAVED_CARD_DISCLOSURE_UNIT_OF_WORK = Symbol("ADMIN_SAVED_CARD_DISCLOSURE_UNIT_OF_WORK");
