export const MESSAGING_STORE = Symbol("MESSAGING_STORE");
export const MESSAGING_READ_STORE = Symbol("MESSAGING_READ_STORE");
export const TELEGRAM_BUSINESS_CONNECTION_LOOKUP = Symbol("TELEGRAM_BUSINESS_CONNECTION_LOOKUP");
export const TELEGRAM_MTPROTO_AUTH_PROVIDER = Symbol("TELEGRAM_MTPROTO_AUTH_PROVIDER");
