export const ORDERS_ORDER_STORE = Symbol("ORDERS_ORDER_STORE");
export const ORDERS_RELATIONSHIP_READER = Symbol("ORDERS_RELATIONSHIP_READER");
export const ORDERS_PRODUCT_STORE = Symbol("ORDERS_PRODUCT_STORE");
export const ORDERS_FINANCE_POLICY_STORE = Symbol("ORDERS_FINANCE_POLICY_STORE");
export const ORDERS_TARIFF_AUTHORITY_STORE = Symbol("ORDERS_TARIFF_AUTHORITY_STORE");
